global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /status

  - job_name: 'backend'
    static_configs:
      - targets: ['backend1:8000', 'backend2:8000', 'backend3:8000', 'backend4:8000']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']